### ISSUE TITLE
[Enhancement] user Can set input and output ip and port

### ISSUE THREAD

**Issue by Monirzadeh** [ProtonVPN/protonvpn-cli-ng#116]
**Is your feature request related to a problem? Please describe.**
Sometimes i should connect to the internet from specific IP and Port Address
or
i don't like all of my connection pass through protonvpn. acsses to protonvpn from specific address can be helpful to pass only specific program thorough protonvpn   
**Describe the solution you'd like**
add a flag to set input and output IP:PORT in protonvpn-cli
it can better if it support Socks5 Socks4 HTTPS and HTTP portocol for input/output trafic
this feature give me a better control over the program that use protonvpn

**Comment by Rafficer** [comment]
Sorry, but I don't understand what you're requesting. What do you mean that you want to set the input/output ip and port?

> it can better if it support Socks5 Socks4 HTTPS and HTTP portocol for input/output trafic

That's not something for the CLI. ProtonVPN itself would need to support this.

**Comment by Monirzadeh** [comment]
1. Some time I need to connect to the internet from specific ip/port (Example: 192.36.36.4:8040) 

2. I need to accesses protonvpn from specific ip instead of all traffic pass through protonvpn so I can set ip and port in proxy settings in the specific programs (Example:127.0.0.1:8041)
Some program doesn't accept Socks5, so it can be better that I have access other option like HTTPS and HTTP too. 
Note: it can be simulating similar function in android app that known as `Split Tunneling`
where should i post This request?
Note: I think at the least number 2 is related.

**Comment by Rafficer** [comment]
> Some time I need to connect to the internet from specific ip/port (Example: 192.36.36.4:8040)

So a proxy?

> I need to accesses protonvpn from specific ip instead of all traffic pass through protonvpn so I can set ip and port in proxy settings in the specific programs (Example:127.0.0.1:8041)
Some program doesn't accept Socks5, so it can be better that I have access other option like HTTPS and HTTP too.

Sorry, I don't know what you mean with that.

> it can be simulating similar function in android app that known as Split Tunneling

It isn't that easy to do on Linux, that's why it's not there.

**Comment by Monirzadeh** [comment]
i wish this diagram can be helpful
![Screanshot-2020-02-12-22-12-30-839903190](https://user-images.githubusercontent.com/25131576/74366305-ffefa880-4de4-11ea-9a5d-69c7edcbfc38.png)
an Example in tor
for Number 1 in this diagram tor has an option `Socks5Proxy` config
for Number 2 in this diagram you can accesses tor on 127.0.0.1:9050

**Comment by Rafficer** [comment]
ProtonVPN just runs an OpenVPN client on your computer, not any kind of server. So this won't happen.
