### ISSUE TITLE
[BUG] protonvpn c -f doesn't choose the fastest server?

### ISSUE THREAD

**Issue by geeknik** [ProtonVPN/protonvpn-cli-ng#122]
**Describe the bug**
From a server in San Francisco, I execute `protonvpn c -f` and it 100% of the time connects me to a server in Georgia, all the way across the country. How is that the fastest server? From my point of view and simple unscientific tests, CA#3 in San Jose would be the fastest server. So how does the client choose the `fastest` server?

**To Reproduce**
1. Provision a VPS in San Francisco through any provider (I used Digital Ocean)
2. Clone this repo
3. Run `protonvpn c -f `
4. See it connect to Georgia

**Expected behavior**
A closer and faster server chosen would make the most sense. 

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
root@sfo2-01:~# protonvpn c --fastest
```
Connecting to US-GA#2 via UDP...
Connected!
root@sfo2-01:~# protonvpn s
Status:       Connected
Time:         0:00:07
IP:           66.115.173.164
Server:       US-GA#2
Features:     Normal
Protocol:     UDP
Kill Switch:  Disabled
Country:      United States
City:         Atlanta
Load:         19%
Received:     16.16 KB
Sent:         5.12 KB
root@sfo2-01:~# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=60 time=64.2 ms
root@sfo2-01:~# ping 9.9.9.9
PING 9.9.9.9 (9.9.9.9) 56(84) bytes of data.
64 bytes from 9.9.9.9: icmp_seq=1 ttl=60 time=63.8 ms
root@sfo2-01:~# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=63.8 ms
root@sfo2-01:~# speedtest-cli
Retrieving speedtest.net configuration...
Testing from Total Server Solutions L.L.C. (66.115.173.164)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Cox - Wichita (Wichita, KS) [43.14 km]: 151.096 ms
Testing download speed
Download: 107.34 Mbit/s
Testing upload speed
Upload: 112.91 Mbit/s
```
Manually connecting to CA#3:

root@sfo2-01:~# protonvpn c
```
Connecting to US-CA#3 via UDP...
Connected!
root@sfo2-01:~# protonvpn s
Status:       Connected
Time:         0:00:05
IP:           209.58.129.99
Server:       US-CA#3
Features:     Normal
Protocol:     UDP
Kill Switch:  Disabled
Country:      United States
City:         San Jose
Load:         22%
Received:     14.84 KB
Sent:         3.55 KB
root@sfo2-01:~# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=59 time=2.20 ms
root@sfo2-01:~# ping 9.9.9.9
PING 9.9.9.9 (9.9.9.9) 56(84) bytes of data.
64 bytes from 9.9.9.9: icmp_seq=1 ttl=58 time=8.87 ms
root@sfo2-01:~# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=55 time=3.16 ms
root@sfo2-01:~# speedtest-cli
Retrieving speedtest.net configuration...
Testing from Leaseweb USA (209.58.129.99)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Cox - Wichita (Wichita, KS) [43.14 km]: 64.031 ms
Testing download speed
Download: 144.89 Mbit/s
Testing upload speed
Upload: 136.12 Mbit/s
```

Speedtest must be confused too since it keeps picking Kansas for the test point.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python Version: 3.75
 - ProtonVPN-CLI Version: 2.2.2

**Additional context**
N/A

**Comment by Rafficer** [comment]
Sadly, this isn't much the CLI can influence. The ProtonVPN API sets a `score` value for each server when the CLI contacts it, the CLI simply sorts by this score value and chooses the server with the highest score.

**Comment by geeknik** [comment]
Is there a way that we can get the CLI to expose this score so that we maybe better understand it and possibly work around this? The only thing I see when manually connecting is a load, but I've found most servers with 100% load tend to be faster than servers with 12% load, of course that is context dependent.

**Comment by Rafficer** [comment]
Check the file `~/.pvpn-cli/serverinfo.json`. That's the data the CLI worked with in the previous connection.

Also, keep in mind that there is no way to really know what server works best. There are way too many variables that can't be influenced, like ISP routing. For this you'd need to connect to every server individually and run a speed test. So the "fastest" server is a rough estimate based on easily obtainable information like server load, estimated distance to the server etc.

**Comment by geeknik** [comment]
Thanks!

**Comment by collinbarrett** [comment]
@Rafficer Does the score that the API returns factor in my current location at all? Or is the score determined purely server-side based on load, etc. at the API? e.g., If I were to theoretically request to connect to the fastest server at exactly the same time from opposite sides of the world, would the API return and connect me to the same server in either case?

**Comment by Rafficer** [comment]
No, you'd get completely different results. Location is probably one of the biggest factors.

**Comment by collinbarrett** [comment]
Hey, @Rafficer , one more question if you don't mind. You [said](https://github.com/ProtonVPN/linux-cli/issues/122#issuecomment-587449102) the cli "chooses the server with the highest score". When I hit the [API](https://api.protonmail.ch/vpn/logicals) directly, it _seems_ like the lowest `Score` would be ideal when comparing to the locations and the `Load`s. Is lower or higher `Score` value considered better/faster/optimal?

Thanks.

**Comment by Rafficer** [comment]
Lower
