### ISSUE TITLE
[BUG] There was an error connecting to the ProtonVPN API.

### ISSUE THREAD

**Issue by commandline-be** [ProtonVPN/protonvpn-cli-ng#128]
**Describe the bug**
After repeat successful init and connect there is a recurrent issue with connecting again. 

The error message [!] "There was an error connecting to the ProtonVPN API." [!] Please make sure your connection is working properly!

Led me to query the API manually, most likely igoring requirements to reliably connect but it shows here there may be an issue with the API connectivity (or i miss the requirements to be met)

wget https://api.protonvpn.ch/vpn/location
--2020-03-04 10:02:56--  https://api.protonvpn.ch/vpn/location
Resolving api.protonvpn.ch (api.protonvpn.ch)... 185.159.159.170
Connecting to api.protonvpn.ch (api.protonvpn.ch)|185.159.159.170|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connecti

**To Reproduce**

protonvpn c

**Expected behavior**

protonvpn connects

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**

wget https://api.protonvpn.ch/vpn/location
--2020-03-04 10:02:56--  https://api.protonvpn.ch/vpn/location
Resolving api.protonvpn.ch (api.protonvpn.ch)... 185.159.159.170
Connecting to api.protonvpn.ch (api.protonvpn.ch)|185.159.159.170|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connection

protonvpn c
 [!] "There was an error connecting to the ProtonVPN API."
 [!] Please make sure your connection is working properly!

**Desktop (please complete the following information):**

Linux OS (Debian based)

**Additional context**

**Comment by commandline-be** [comment]
Running testssl.sh it is shown api.protonvpn.ch does not offer TLS at this time, this completely breaks protonvpn-cli, i cannot be the only one experiencing this.

**Comment by Rafficer** [comment]
Please check your device and network for this. There's not much the CLI can do if you generally can't connect to their API.

**Comment by commandline-be** [comment]
> Please check your device and network for this. There's not much the CLI can do if you generally can't connect to their API.

Thanks. After reinstall it works fine once, then the API is no longer reachable.

**Comment by Rafficer** [comment]
And you can't open with with curl/wget either? Can you open it in your browser?

Which Distro are you using?

Can you try to disable DNS Leak Protection via `protonvpn configure` before making the first connection?

**Comment by commandline-be** [comment]
Apparently the customer network i was on had a multi day outage which was on and kept or reject all sessions, tested on mobile phone tether and all is well. It does not make sense to me. The error reoccurred on mobile tether initally, after reinstall and removing all artefacts all is well again.

**Comment by Rafficer** [comment]
Awesome. Can you close this issue when you think it's resolved? :)

**Comment by commandline-be** [comment]
I leave it at this. I still think it is a somewhat shabby script. Protonvpn should offer it as a package to simply start a service with a user exposed ui ... or something. No time to work on this myself.

**Comment by commandline-be** [comment]
Removal and purging of all configuration artefacts followed be reinstallation and a new init appeared to have resolved the issue.
