### ISSUE TITLE
[BUG] UFW disables on reboot with killswitch enabled

### ISSUE THREAD

**Issue by originalhotpocket** [ProtonVPN/protonvpn-cli-ng#131]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
If applicable, add error messages or output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Debian 9]
 - Python Version: [e.g. 3.7.4 (`python3 --version`)]
 - ProtonVPN-CLI Version: [e.g. 2.2.2 (`protonvpn --version`)]

**Additional context**

**Comment by Rafficer** [comment]
Please fill out the form properly to give more information.

**Comment by Rafficer** [comment]
Not enough information.
