### ISSUE TITLE
[BUG] Protonvpn not working after PC suspension

### ISSUE THREAD

**Issue by Juankz** [ProtonVPN/protonvpn-cli-ng#136]
**Describe the bug**
When suspending and then waking up my machine, protonvpn stops working. I have to manually disconnect it and reconnect it.

**To Reproduce**
1. Connect to vpn normally `protonvpn c`
2. Verify you can access internet
3. Suspend machine
4. Wakeup machine from suspension
5. Try access internet -> This fails

**Expected behavior**
Protonvpn should recover after machine suspension.

**Desktop (please complete the following information):**
 - OS: Solus 4.1
 - Python Version: 3.7.6
 - ProtonVPN-CLI Version: 2.2.2

PS: ProtonVPN is very cool, you are awesome

**Comment by Rafficer** [comment]
This needs a background daemon, as mentioned in #28. Please refer to that issue.
