### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sreejithgk94** [ProtonVPN/protonvpn-cli-ng#137]
hi 
i have an issue in  proton vpn after install on my centos 8. Ifollowed below step

On Fedora / CentOS / RHEL, please use:
sudo dnf install -y openvpn dialog python3-pip python3-setuptools

sudo pip3 install protonvpn-cli

 protonvpn-cli init
bash: protonvpn-cli: command not found...

**Comment by Rafficer** [comment]
Please follow these instructions: https://github.com/ProtonVPN/protonvpn-cli-ng/issues/64#issuecomment-565844773

**Comment by sreejithgk94** [comment]
Let me try
