### ISSUE TITLE
[Enhancement] Distribute packages through community repos

### ISSUE THREAD

**Issue by syscll** [ProtonVPN/protonvpn-cli-ng#142]
**Describe the solution you'd like**
As it stands, we install `protonvpn-cli-ng` via PyPI- which is not an issue at all.

While I understand this might not be a priority, would you also consider distributing via community repos, such as the [AUR](https://aur.archlinux.org/)?

>The AUR (Arch User Repository) is a place where the Arch Linux community can upload PKGBUILDs of applications, libraries, etc., and share them with the entire community. Fellow users can then vote for their favorites to be moved into the community repository to be shared with Arch Linux users in binary form.

In my opinion, allowing installation through official/community repos allows user's to easily stay up-to-date with the latest versions of software.

**Additional context**
I would be more than happy to help or get involved in any tasks required to facilitate this. 

Here are some useful AUR links for context:
- https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages
- https://wiki.archlinux.org/index.php/AUR_submission_guidelines

**Comment by Rafficer** [comment]
There are packages available on the AUR, maintained by other community members.

**Comment by syscll** [comment]
So there are, thanks!

https://aur.archlinux.org/packages/protonvpn-cli-ng
