### ISSUE TITLE
[Enhancement] GU size change for smaller screens

### ISSUE THREAD

**Issue by anthonyh-uk** [ProtonVPN/protonvpn-cli-ng#146]
I use a smaller laptop with 1368 x 768 and find the GUI will not fit reasonably on the page.

I’m not a programmer but I’m so impressed with this software that I’m hoping there’s a way to shrink it a bit smaller for us small screen users.

Perhaps reducing the font size in the upper section?  I’m not sure what’s possible and accept there may be other priorities.

Either way keep up the good work.

**Comment by Rafficer** [comment]
Can you post a screenshot? That resolution should be plenty enough.

**Comment by anthonyh-uk** [comment]
![Screenshot at 2020-04-02 05-36-20](https://user-images.githubusercontent.com/63021385/78211205-39b76400-74a4-11ea-9454-b60f3b0c804a.png)

**Comment by calexandru2018** [comment]
Hello @anthonyh-uk, this is issue related to [protonvpn-linux-gui](https://github.com/calexandru2018/protonvpn-linux-gui) and not the CLI. For GUI issues, please post it on the previous mentioned link.

**Comment by anthonyh-uk** [comment]
Thanks, will do.
