### ISSUE TITLE
[BUG] Just did a fresh install from pip, getting ModuleNotFoundError.

### ISSUE THREAD

**Issue by Phate6660** [ProtonVPN/protonvpn-cli-ng#15]
**Describe the bug**
As the title says. Though I think I may know the problem. I'm on Gentoo, so I can't install `protonvpn-cli` globally. I have to use `pip3 install --user protonvpn-cli` instead.

**To Reproduce**
1. Install with the `--user` option in `pip3`.
2. Run the command `sudo $HOME/.local/bin/protonvpn c -f`
3. See error

**Expected behavior**
I expected the cli to connect to the vpn.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
```
Traceback (most recent call last):
  File "/home/valley/.local/bin/protonvpn", line 6, in <module>
    from protonvpn_cli.cli import main
ModuleNotFoundError: No module named 'protonvpn_cli'
```

**Desktop (please complete the following information):**
 - OS: Gentoo
 - Python Version: 3.6.9
 - ProtonVPN-CLI Version: 2.1.0

**Comment by Rafficer** [comment]
The problem is that when you run it as sudo it looks in roots site-packages for the module. As that doesn't exist, it fails. That's the reason why it needs to be run with sudo.

Why is that not possible with Gentoo?

**Comment by Phate6660** [comment]
Because Gentoo itself sends you an error and forces you to use `--user`, unless there's a way around it that I didn't know about.

`$ sudo pip3 install protonvpn-cli`
```
ERROR: (Gentoo) Please run pip with the --user option to avoid breaking python-exec
```

**Comment by Rafficer** [comment]
And if you log in as root and then install it with the root account?

**Comment by Phate6660** [comment]
It is working now, thank you. I don't why I didn't think of that.

I was still forced to use `--user`, but since it was on the root account it still installed as the root user anyways.

----

Ok, well it looked like it was working but now I get this error after connecting. Because of this error I can not connect nor disconnect.
```
Traceback (most recent call last):
  File "/root/.local/bin/protonvpn", line 10, in <module>
    sys.exit(main())
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/cli.py", line 72, in main
    cli()
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/cli.py", line 106, in cli
    connection.fastest(protocol)
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/connection.py", line 149, in fastest
    disconnect(passed=True)
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/connection.py", line 341, in disconnect
    manage_dns("restore")
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/connection.py", line 612, in manage_dns
    oldhash = get_config_value("metadata", "resolvconf_hash")
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/utils.py", line 112, in get_config_value
    return config[group][key]
  File "/usr/lib64/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'resolvconf_hash'
```

**Comment by Rafficer** [comment]
can you run `sudo PVPN_DEBUG=1 protonvpn c -f ` and send me the full output? Or without sudo, however you did it now.

**Comment by Phate6660** [comment]
`$ sudo PVPN_DEBUG=1 /root/.local/bin/protonvpn c -f`
```
2019-11-16 10:16:46,654 — protonvpn-cli — DEBUG — cli:84 — ###########################
2019-11-16 10:16:46,654 — protonvpn-cli — DEBUG — cli:85 — ### NEW PROCESS STARTED ###
2019-11-16 10:16:46,655 — protonvpn-cli — DEBUG — cli:86 — ###########################
2019-11-16 10:16:46,655 — protonvpn-cli — DEBUG — cli:87 — ['/root/.local/bin/protonvpn', 'c', '-f']
2019-11-16 10:16:46,655 — protonvpn-cli — DEBUG — cli:88 — Arguments
{'--cc': None,
 '--fastest': True,
 '--help': False,
 '--p2p': False,
 '--random': False,
 '--sc': False,
 '--tor': False,
 '--version': False,
 '-p': None,
 '<servername>': None,
 'c': True,
 'configure': False,
 'connect': False,
 'd': False,
 'disconnect': False,
 'examples': False,
 'init': False,
 'r': False,
 'reconnect': False,
 'refresh': False,
 's': False,
 'status': False}
2019-11-16 10:16:46,655 — protonvpn-cli — DEBUG — cli:89 — USER: valley
2019-11-16 10:16:46,655 — protonvpn-cli — DEBUG — cli:90 — CONFIG_DIR: /home/valley/.pvpn-cli
2019-11-16 10:16:46,669 — protonvpn-cli — DEBUG — fastest:144 — Starting fastest connect
2019-11-16 10:16:46,670 — protonvpn-cli — DEBUG — disconnect:304 — Initiating disconnect
2019-11-16 10:16:46,675 — protonvpn-cli — DEBUG — is_connected:178 — Checking connection Status. OpenVPN processes: 0
2019-11-16 10:16:46,675 — protonvpn-cli — DEBUG — manage_dns:608 — Restoring DNS
Traceback (most recent call last):
  File "/root/.local/bin/protonvpn", line 10, in <module>
    sys.exit(main())
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/cli.py", line 72, in main
    cli()
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/cli.py", line 106, in cli
    connection.fastest(protocol)
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/connection.py", line 149, in fastest
    disconnect(passed=True)
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/connection.py", line 341, in disconnect
    manage_dns("restore")
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/connection.py", line 612, in manage_dns
    oldhash = get_config_value("metadata", "resolvconf_hash")
  File "/root/.local/lib64/python3.6/site-packages/protonvpn_cli/utils.py", line 112, in get_config_value
    return config[group][key]
  File "/usr/lib64/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'resolvconf_hash'
```

**Comment by Rafficer** [comment]
Wow, you must have encountered some edge case where a file was written before it's value in the config file could be updated before.

Can you delete the file `~/.pvpn-cli/resolv.conf.backup`, that should remove this error.

If another error like this happens after that, please attach the output of `ls -lah ~/.pvpn-cli/` and the output of `cat ~/.pvpn-cli/pvpn-cli.cfg`.

**Comment by Phate6660** [comment]
Thank you, deleting the file worked. I can now connect to the VPN.

I know this is separate from the issue, but I noticed that in the status it states:
`Killswitch:   Disabled`

Does that mean there is killswitch functionality, or is that a placeholder and it isn't implemented yet?

**Comment by Rafficer** [comment]
Great to hear.

There actually is a Kill Switch. Check out `protonvpn configure`. This will be more clear from ProtonVPN's announcements in the near future and when I add more documentation.

**Comment by Rafficer** [comment]
Btw, can you maybe describe in a bit more detail what exactly you did to get it working now? This would be very very helpful in the future, I doubt you will be the only one running into this issue with Gentoo.

Also, would you mind telling me how you came across this program? For some reason downloads exploded in the past 3-4 days without any announcement. So I'm just curious how this spread so fast :P

**Comment by Phate6660** [comment]
> Btw, can you maybe describe in a bit more detail what exactly you did to get it working now?
1. I logged into root with `su` (for some reason `sudo -i` was acting weird).
2. Ran the command `pip3 install --user protonvpn-cli`.
3. I have to run the command as `sudo /root/.local/bin/protonvpn` as for some reason that dir didn't want to be added to my $PATH. (I'm sure I can add it, I'm just too lazy right now to figure out where to place it.)
4. That should be all, but I had the `resolv.conf.backup` problem as well (though I feel like that issue was specific to me).

> Also, would you mind telling me how you came across this program?

Github just happened to place it in my /explore page, and I just happened to come across it.
After that, I checked the support page for the cli on the official ProtonVPN site and noticed that the guide was updated for the "2.0" version of the cli. So I decided to try it out.

----

Anyways, thank you for your help and the info on the killswitch. I believe everything is done here, so I'll close the issue. Open it back up if you need any more info from me, I'm more than happy to help. Hope you have a great day. :)

**Comment by Rafficer** [comment]
I was having some thoughts about this as I didn't really like the way it was solved. As I'm not having a Gentoo VM rn, could you maybe test this for me?

___

## Install

1. Create a directory for the Installation and step into it (doesn't matter where it is as long as you got access to it)

    `mkdir ~/Documents/ProtonVPN-CLI`

    `cd ~/Documents/ProtonVPN-CLI`

2. Install the virtualenv package

    `pip3 install virtualenv --user`

3. Create a virtual envirnoment and activate it

    `virtualenv .venv`

    `source .venv/bin/activate`

4. Now that you're in the virtual environment, install ProtonVPN-CLI

    `pip install protonvpn-cli`

    As you're in the virtualenv, `pip` should be the same as `pip3`. Also **don't** use sudo here.

5. You should now have the executable `.venv/bin/protonvpn`. Maybe check it with a status print.

    `sudo .venv/bin/protonvpn status`

6. If that works, deactivate the virtual environment again

    `deactivate`

7. Now link the executable from above to a PATH folder so you can access it from anywhere

    `sudo ln -sf ~/Documents/ProtonVPN-CLI/.venv/bin/protonvpn /usr/local/bin/protonvpn`

Now you should be able to use the protonvpn command from anywhere in the system without issues.

## Updating

1. Activate the virtual environment again

    `source ~/Documents/ProtonVPN-CLI/.venv/bin/activate`

2. Update ProtonVPN-CLI

    `pip install protonvpn-cli --upgrade`

3. Deactivate the virtual environment

    `deactivate`

## Uninstall

1. Purge configuration

    `sudo protonvpn configure` -> `7` -> `y`

2. Delete the ProtonVPN-CLI folder

    `rm -rf ~/Documents/ProtonVPN-CLI`

3. Delete the symlink

    `sudo unlink /usr/local/bin/protonvpn`
    `

___

I think this is a far cleaner approach (given that it works) than what you did before. Would be great if you could give some feedback on how it turned out. If it really works flawlessly I think this is worth adding to the USAGE.md file for future reference.

**Comment by Phate6660** [comment]
Yep, this worked flawlessly. I like this way much better.

**Comment by Rafficer** [comment]
Awesome, thanks for your feedback!
