### ISSUE TITLE
[BUG] Enabling split tunneling doesn't disable the kill switch, as stated

### ISSUE THREAD

**Issue by RememberTheAir** [ProtonVPN/protonvpn-cli-ng#154]
**Describe the bug**

Title is a bit misleading because I couldn't fit a correct explanation in it: the cli says that enabling split tunneling will disable the kill switch, which is fine. Doing so will actually disable it in `~/.pvpn-cli/pvpn-cli.cfg`, but `protonvpn status` shows that the kill-switch is still enabled

**To Reproduce**

1. use `protonvpn configure`
2. enable kill-switch
3. enable split tunneling. The cli will tell you that the kill-switch will be disabled because the two options are not compatible
4. use `protonvpn status`

**Expected behavior**
`protonvpn status` will show you that the kill-switch is disabled

**Error Messages/Program Output/Log Messages**
`protonvpn status` will show you that the kill-switch is enabled, but apparently it has actually been disabled, as stated by the program when enabling split tunneling (in fact, `~/.pvpn-cli/pvpn-cli.cfg` shows it as disabled)

**Desktop (please complete the following information):**
 - OS: Raspbian 9.6
 - Python Version: 3.6.0
 - ProtonVPN-CLI Version: 2.2.2

**Comment by Rafficer** [comment]
Is this still happening after you reconnect?

**Comment by RememberTheAir** [comment]
@Rafficer yep

**Comment by Rafficer** [comment]
Sorry, I'm under the impression that you misunderstand something.

When you use `configure` to disable the Kill Switch, that change will only be active on the next connection.

![image](https://user-images.githubusercontent.com/19485606/79672144-bd28c300-81cf-11ea-812a-e953a56f9e97.png)

1. I've first enabled split tunneling, which disabled the Kill Switch.
2. Still being connected, it tells me that the Kill Switch is enabled (which is correct, as it's still active
3. Then I reconnect
4. Now it tells me the Kill Switch is not enabled anymore.

Does that make sense?

**Comment by RememberTheAir** [comment]
You are right, tested again and re-connecting will update the output of `protovpn s` (I probably re-enabled the killswitch manually and didn't remember). I thought disabling/enabling the kill-switch and split tunneling would update my config in-place but I need to reconnect first, got it
