### ISSUE TITLE
[Enhancement] Ask about Kill Switch when Initializing

### ISSUE THREAD

**Issue by sojusnik** [ProtonVPN/protonvpn-cli-ng#24]
ATM the Kill Switch can only be enabled after using `configure`, but why not ask about it when initializing with `init`?

**Comment by Rafficer** [comment]
To not overwhelm the user. The initialization process is just for setting up the ProtonVPN credentials and creating the base file structure the CLI needs.

Asking the user about every possible setting is a very bad choice, if someone wants to enable the Kill Switch before connecting, they can easily do so.

This behavior is also consistent with all other ProtonVPN clients.
