### ISSUE TITLE
Don't reveal true IP when establishing a connection

### ISSUE THREAD

**Issue by sojusnik** [ProtonVPN/protonvpn-cli-ng#25]
I'm using the Kill Switch, but observe that while establishing a VPN connection my true IP is disclosed. Is there a way to hide it while doing so?

The aim is to only go online through a VPN, never revealing the true IP.

**Comment by Rafficer** [comment]
This is impossible. You need your "true" IP to establish a VPN connection, that's how the internet works.

**Comment by sojusnik** [comment]
Sounds reasonable, but I had the impression when using the Network Manager on Ubuntu (`nm-connection-editor` > choose your ethernet connection > go to first tab > enable "automatically connect with VPN") then the connection is only established through the VPN.

**Comment by Rafficer** [comment]
With that option the VPN just automatically connects after the ethernet connection comes up. There's still a delay between the connection coming up and the VPN tunnel being established.

Can this be closed?

**Comment by Rafficer** [comment]
Just cause it came to my mind right now: what you seem to want/need is a router that handles the VPN connection in front of your device. Then everything will go over the VPN all the time.

But it's not achievable by this program.

**Comment by sojusnik** [comment]
Thanks for the reminder! Configuring a VPN connection on my ASUS router is already on my to-do list.
