### ISSUE TITLE
[Enhancement] Persistent notification when connection is lost

### ISSUE THREAD

**Issue by sojusnik** [ProtonVPN/protonvpn-cli-ng#26]
As I often experience connection drops, it would be very helpful to have a persistent notification (f.i. through `notify-send`) to be notified of them, because at the moment there's no graphical feedback if a VPN connection is established or not, like f.i. in Gnome's Network Manager.

As a workaround, I use [this](https://extensions.gnome.org/extension/1677/public-ip/) Gnome extension to see the IP or/and country flag.

**Comment by Rafficer** [comment]
ProtonVPN-CLI has no way of knowing when a connection is down. I have created above linked issue to solve this in the future with a daemon.
