### ISSUE TITLE
[Enhancement] macOS Support

### ISSUE THREAD

**Issue by n3dj0** [ProtonVPN/protonvpn-cli-ng#31]
The previous [CLI](https://github.com/ProtonVPN/protonvpn-cli) had support for macOS. This one doesn't. Are there any plans to add macOS support in the future?

**Comment by Rafficer** [comment]
I can't speak for the Proton team now, but I personally don't think their opinion differs from mine.

I don't plan to and also can't support macOS as I don't have a device running macOS. Apart from that future developments might make it too difficult to support or outright impossible to support every feature on macOS.

ProtonVPN has a GUI client available for macOS and should be the client used on this platform.

**Comment by n3dj0** [comment]
Thank you for the fast answer, Rafficer

**Comment by jonathancross** [comment]
> ProtonVPN has a GUI client available for macOS and should be the client used on this platform.

Unfortunately, `protonvpn-cli-ng` offers many features not supported by the GUI such as split tunneling.

**Comment by sanderdekoning** [comment]
Seems like a big step backwards to me; I'm sure there are more developers on MacOS that would welcome, or much prefer, the CLI version of ProtonVPN

**Comment by AnCh7** [comment]
+1
Please provide macos support!

**Comment by calexandru2018** [comment]
MacOS has its own client, therefore, no support for that platform will be added in the near future.
