### ISSUE TITLE
[BUG] DNS leak protection potentially breaks name resolution when restoring resolv.conf from backup

### ISSUE THREAD

**Issue by 70rc** [ProtonVPN/protonvpn-cli-ng#32]
**Describe the bug**
Systems that use systemd's resolved use a symlink from /etc/resolv.conf to /run/systemd/resolve/resolv.conf (or similar). The current implementation of the DNS leak protection restores the original resolv.conf from a backup file, resulting in resolv.conf now being a static file with the original content rather than a symlink to the resolv.conf managed by resolved.
Worse even, on Linux Mint no DNS behaviour is configured in NetworkManager, relying on its default of not touching resolv.conf if it is a symlink to systemd's resolv.conf (see https://developer.gnome.org/NetworkManager/stable/NetworkManager.conf.html). This results in resolv.conf now suddenly being managed by NM instead of systemd because it is no longer a symlink. A reboot does not restore the symlink.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable DNS leak protection
2. sudo protonvpn c -f
3. sudo protonvpn d

**Expected behaviour**
Restore the symlink instead of a static file. I understand that this will mess with the current behaviour of checking the hash. So I think a check should be performed whether resolv.conf is a symlink. If yes, just store its target location and restore the link without bothering about the actual contents. The backend managing the link target should take care of the contents.
A second option would be the old protonvpn-cli behaviour of overwriting the target file. Maybe this is just a setting in the python copy method to follow the link instead of overwriting it. However, personally I think temporarily replacing the symlink with a static file could have the advantage of preventing the backend to mess with the file. On the other hand, NM might do so anyway...

**Desktop:**
 - OS: Linux Mint 19.2 Tina
 - Python Version: 3.6.8
 - ProtonVPN-CLI Version: 2.1.1

**Additional context**
I know resolv.conf management is notoriously painful. Otherwise I really like the new version. It is a huge improvement.
As a side note: In addition, the immutable attribute could be set on resolv.conf to prevent any other program from touching it.

**Comment by 70rc** [comment]
Just checked the original link target (/run/systemd/resolve/resolv.conf). There is a comment stating the following:
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.

So I guess the ideal behaviour would be to write the protonvpn resolv.conf to a separate file and point the symlink to that, and back when disconnecting.

**Comment by Rafficer** [comment]
Thanks for opening this issue. I will work on this over the weekend and hope this is resolved by next week.

I'm just not sure whether or not to save and restore the symlink itself or overwrite the target file.

Will see what works better and more consistent.

**Comment by khicks** [comment]
I'm on Ubuntu 18.04 and looking to switch away from another major VPN provider. I had their desktop client set up with a the symlink `/etc/resolv.conf -> /run/systemd/resolve/stub-resolv.conf`. After trying the PVPN CLI-ng, my old VPN wasn't working anymore and it was driving me bonkers. Turns out the replacement of `resolv.conf.backup` to a static file was the culprit.

**Comment by Rafficer** [comment]
I know and I'm sorry this happened. I fixed the bug and just wait for a merge and release tomorrow.

**Comment by khicks** [comment]
No worries! Thanks for fixing it so quickly!
