### ISSUE TITLE
[BUG] Directly connecting to a server under maintenance without using the TUI leads to a crash

### ISSUE THREAD

**Issue by 70rc** [ProtonVPN/protonvpn-cli-ng#35]
**Describe the bug**
protonvpn-cli-ng crashes when trying to connect to a server under maintenance with `protonvpn connect <server>`

**To Reproduce**
1. `sudo protonvpn c <serverUnderMaintenance>`

**Expected behavior**
Throw an error that the respective server is under maintenance.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
```
$ sudo protonvpn c chat1
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 72, in main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 108, in cli
    connection.direct(args.get("<servername>"), protocol)
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/connection.py", line 273, in direct
    .format(servername),
KeyError: 'servername'
```
[pvpn-cli.log](https://github.com/ProtonVPN/protonvpn-cli-ng/files/3875683/pvpn-cli.log)

**Desktop:**
 - OS: Linux Mint 19.2 Tina
 - Python Version: 3.6.8
 - ProtonVPN-CLI Version: 2.1.1

**Comment by Rafficer** [comment]
Thanks for reporting this. This also happens when using an invalid server name.

Next release seems to get quite a few important bug fixes... :)

**Comment by 70rc** [comment]
Awesome response time!
