### ISSUE TITLE
Authentication failed.

### ISSUE THREAD

**Issue by MegaaVladd** [ProtonVPN/protonvpn-cli-ng#50]
ProtonVPN-CLI version: v2.1.2
OS: Ubuntu64 19.10

I cannot make Authentication although my password is exactly correct. 
I have alert:  
[!] Authentication failed. 
[!] Please make sure that your Username and Password is correct.
When I login through desktop-client on mac or windows then my authentication is ok, but I also enter the password for my mailbox protonmail when I login in my account for protonvpn that is, I enter two password. On ubuntu proton CLI I enter only one password for protonvpn

**Comment by Rafficer** [comment]
As the message when you initialize says, you can't use your normal ProtonMail/VPN login password for this. You need to use your OpenVPN credentials. You can find them on https://account.protonvpn.com/account. The [example installation](https://github.com/ProtonVPN/protonvpn-cli-ng/blob/master/USAGE.md#example-installation-on-ubuntu-1804) also shows this.

**Comment by MegaaVladd** [comment]
Oh, I'm so sorry, I was on attentive.
Thank you very much

**Comment by Rafficer** [comment]
I guess this solved the problem? I'll close this issue then.

**Comment by conkerts** [comment]
Thank you.

But instead of "only" writing this error msg
> [!] Authentication failed.
> [!] Please make sure that your Username and Password is correct.

I'd appreciate a hint, that it should be the OpenVPN cred (ideally in red).

**Comment by calexandru2018** [comment]
@conkerts it's actually written in the text right before.

**Comment by conkerts** [comment]
Yes it is, I wont dispute that.
And still I didn't see it 😂
It needs to be red, or bold or something ...
