### ISSUE TITLE
[BUG] pvpn is missing (instead protonvpn is available)

### ISSUE THREAD

**Issue by u666sa** [ProtonVPN/protonvpn-cli-ng#54]
**Describe the bug**
On my other laptop I have ProtonVPN version 1.1.2 and I am able to use pvpn -c command to connect. It has a clear, usable interface. This new latest version 2.1.2 is a) does not have pvpn command (I got command not found when I type pvpn) and b) has a crappy interface when compared to version 1.1.2

**To Reproduce**
Go to terminal and type pvpn..
bash: pvpn: command is missing
Go to protonpvpn client interface, and compare it to version 1.1.2 you will see that the new interface is crap.

**Expected behavior**
I want pvpn command back! and I want old interface back!

**Desktop (please complete the following information):**
Fedora 31

**Additional context**
pvpn it's easy to type

**Comment by Rafficer** [comment]
Those two things aren't bugs but intended.

The interface is grouped by countries, like all other ProtonVPN applications as well.

It's nonsensical to add different commands for the exact same executable. This is what Linux has aliases for, so every user can choose themselves what they want to type to call a certain program. There's [a guide here](https://github.com/ProtonVPN/protonvpn-cli-ng/blob/master/USAGE.md#configure-alias-for-quicker-access) that shows how you can set up aliases for ProtonVPN-CLI.
