### ISSUE TITLE
Ownership of install folders in Home directory - installation warning

### ISSUE THREAD

**Issue by Jakethethird** [ProtonVPN/protonvpn-cli-ng#55]
I get the message below upon installing in Ubuntu 18.04

jake@jtp-x1c6:~$ sudo pip3 install protonvpn-cli
The directory '/home/jake/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jake/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Should I rerun with the sudo -H flag? Uninstall and reinstall with the -H flag? or just leave it alone?

Thanks,
Jake

**Comment by Rafficer** [comment]
Leave it alone. PIP typically caches downloads (so if you install something 3 times in different locations, it only downloads it once). This message basically says the cache is disabled so it would actually download it 3 times.

That's nothing to worry about.
