### ISSUE TITLE
[BUG] Version pip

### ISSUE THREAD

**Issue by cantalupo555** [ProtonVPN/protonvpn-cli-ng#58]
I am already using the latest version, but still have this warning.

"You are using pip version 18.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."

![](https://i.imgur.com/TtvOQdp.jpg)

![](https://i.imgur.com/WoA1SgY.jpg)

![](https://i.imgur.com/OxKsvWh.jpg)

**Comment by Rafficer** [comment]
Has nothing to do with ProtonVPN. This is just the Python package manager giving a warning that there's a new version available. Feel free to ignore it.
