### ISSUE TITLE
[BUG] Not working on OSX due to missing "ip" command

### ISSUE THREAD

**Issue by budlight** [ProtonVPN/protonvpn-cli-ng#60]
**Describe the bug**

sudo protonvpn init does not work gives output:

```
'ip' not found. 
 Please install ip.
```

**To Reproduce**
```
sudo pip3 install protonvpn-cli
sudo protonvpn init
```

**Expected behavior**
For it to work

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6 Mojave
 - Python Version: Python 3.7.5
 - ProtonVPN-CLI Version: ProtonVPN-CLI v2.1.2

**Additional context**
I do have the gui client installed as well, but can't see how that would change anything.

**Comment by Rafficer** [comment]
MacOS is not supported and probably won't be, as explained in #31.

Sorry.
