### ISSUE TITLE
[BUG] OpenBSD - ifconfig(8) support

### ISSUE THREAD

**Issue by wonderboom** [ProtonVPN/protonvpn-cli-ng#73]
**Bug description**

protonvpn-cli-ng requires ip(8) and doesn't support ifconfig(8), thus not supporting OpenBSD.

**To Reproduce**

Steps to reproduce:
1. Install protonvpn-cli 2.2.0, as root, via pip3.
2. Run `doas protonvpn init`
3. See error

**Expected behavior**

protonvpn 2.0 should connect to the ProtonVPN servers via ifconfig(8)

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**

`doas protonvpn init`
`'ip' not found.`
 `Please install ip.`

**Desktop (please complete the following information):**

 - OS: [OpenBSD 6.6 (-STABLE)]
 - Python Version: [3.7.4]
 - ProtonVPN-CLI Version: [2.2.0]

**Comment by SteveClement** [comment]
I would argue this applies to more than OpenBSD, older (LTS) Linux systems will not have IP out of the box.
This is a matter of a simple RegEX addition, thus PR please ;)

**Comment by Rafficer** [comment]
I'll close this in favor of #111. So for further discussion, please go there. :)
