### ISSUE TITLE
[BUG] Split tunneling should take precedence over Kill Switch

### ISSUE THREAD

**Issue by c4f3a0ce** [ProtonVPN/protonvpn-cli-ng#74]
At the moment enabling kill switch renders split tunneling settings useless.

**Steps to reproduce the behavior**:
1. `protonvpn  configure`
2. Choose 5, set to 2.
3.  `protonvpn  configure`
4. Choose 6, y, add IP address
5. IP address added in 4. cannot be reached. For example `ping` gives:

    ```
    ping: sendmsg: Operation not permitted
    ```

**Expected behavior**

I should be able to reach the given host.

**Comment by Rafficer** [comment]
Yeah, I'm probably going to display a notice and disable the other if one is activated.

They can't properly work together.

**Comment by c4f3a0ce** [comment]
Thanks for the prompt response! That's good to know. Is there any chance for having a special case for #75? :)
