### ISSUE TITLE
[Enhancement] Automatically reconnect after waking up from sleep.

### ISSUE THREAD

**Issue by vinliao** [ProtonVPN/protonvpn-cli-ng#77]
**Is your feature request related to a problem? Please describe.**
I noticed that my laptop's internet doesn't work after I woke it up from sleep, even though the internet works on other device. When I ran `protonvpn status`, it told me to run `protonvpn reconnect`.

**Describe the solution you'd like**
It would be nice to have it automatically reconnect every time it wakes up from sleep.

**Describe alternatives you've considered**
Another alternative solution for this problem is by creating a script to automatically reconnect in `rc.local`.

**Comment by Rafficer** [comment]
Please refer to #28.
