### ISSUE TITLE
[Enhancement] Add better support for custom window manager "docks"

### ISSUE THREAD

**Issue by jwflory** [ProtonVPN/protonvpn-cli-ng#80]
**Is your feature request related to a problem? Please describe.**

I use the [i3 tiling window manager](https://i3wm.org/). It ships software called `i3bar` which is a collection of strings arranged in a dock however the user wants. I want to add a quick indicator to my "dock" if my VPN is connected or not.

**Describe the solution you'd like**

`protonvpn status` could offer flags for each of the specific fields it prints. For example:

```bash
$ protonvpn status
Status:       Connected
Time:         0:02:05
IP:           redacted
Server:       redacted
Features:     redacted
Protocol:     redacted
Kill Switch:  redacted
Country:      redacted
City:         redacted
Load:         33%
```

I could script something like this to print status into my dock:

```bash
$ protonvpn status --connection
Connected
```

**Describe alternatives you've considered**

Alternatively, `protonvpn status` could emit an exit code of `1` if the VPN is disconnected. This would register as an error in the shell. This approach allows me to do a boolean check if the VPN is connected, and then add whatever I text I choose (instead of hard-coding a `Connected` string into my dock).

For example, current behavior:

```bash
$ protonvpn status
[ any output ]
$ echo $?
0
```

What my alternative suggestion looks like:

```bash
$ protonvpn status
Status:       Connected
[output]
$ echo $?
0
```

```bash
$ protonvpn status
Status:       Disconnected
[output]
$ echo $?
1
```

This comes at a potential cost of whether you want to emit a non-zero exit code here though.

**Additional context**

I wanted to say this tool is awesome and made ProtonVPN doubly awesome for me as a Linux user. Awesome job.

I created an RPM package for Fedora, CentOS, and RHEL users in [this COPR repository](https://copr.fedorainfracloud.org/coprs/jflory7/protonvpn-cli/). Sometime in early 2020, I'll work on packaging it officially for Fedora/EPEL too.

**Comment by Rafficer** [comment]
What the status print does is essentially just check whether or not a process called `openvpn` is running, which can be seen [here](https://github.com/ProtonVPN/protonvpn-cli-ng/blob/80a4c6db11ccebd3c95cce4b9e5e6be586cca290/protonvpn_cli/connection.py#L355) and [here](https://github.com/ProtonVPN/protonvpn-cli-ng/blob/80a4c6db11ccebd3c95cce4b9e5e6be586cca290/protonvpn_cli/utils.py#L192).

So you could just do `pgrep openvpn` and then check the return code, which is `1` when that process doesn't exist and `0` when it does exist.

> I wanted to say this tool is awesome and made ProtonVPN doubly awesome for me as a Linux user. Awesome job.

Thank you. Really glad to hear that! 🙂 

> I created an RPM package for Fedora, CentOS, and RHEL users in this COPR repository. Sometime in early 2020, I'll work on packaging it officially for Fedora/EPEL too.

Really cool, thanks! Though, how does it manage the python dependencies? I don't think the docopt package is available, is it?

**Comment by jwflory** [comment]
> So you could just do pgrep openvpn and then check the return code, which is 1 when that process doesn't exist and 0 when it does exist.

Thanks, this is exactly what I wanted. I'll go ahead and close this issue and script this out.

> Really cool, thanks! Though, how does it manage the python dependencies? I don't think the docopt package is available, is it?

Fedora carries a `python3-docopt` package, although I am not currently bundling it as a run-time or build-time package. If you want to see my work-in-progress RPM spec, here it is:

https://github.com/jwflory/rpmbuild/blob/add/protonvpn-cli/rpmbuild/SPECS/protonvpn-cli.spec
