### ISSUE TITLE
[Enhancement] How should client react to server maintenance?

### ISSUE THREAD

**Issue by Mitchellpkt** [ProtonVPN/protonvpn-cli-ng#81]
I use MacOS v1.5.3, but the following probably applies to other versions.

When the server I was connected to switched to maintenance mode, I didn't have any notice besides my internet connection dying. Since the ProtonVPN icon in my status bar was showing the successful connection checkmark, it took me a few minutes of troubleshooting before I manually checked the server status and identified the issue.

Wondering about different ways to handle this:
-  Stay connected to server with no connection (current experience)
-  Pop a warning to notify the user
-  Automatically reconnect to another server

If in "quick connect" mode, switching to another server would probably be fine. I use 5 specific servers, so in my case a warning would be more helpful. (however, I'm probably the edge case)

Thoughts?

**Comment by Rafficer** [comment]
ProtonVPN-CLI currently has no background service, so it can't display warnings, nor reconnect automatically. A background service is planned, as documented in #28 .

> I use MacOS v1.5.3

Also, just saying, macOS isn't officially supported.

**Comment by Mitchellpkt** [comment]
Oops, I was linked to the package from [protonvpn.com](protonvpn.com), so I assumed it was official software. Nevermind. :- )

**Comment by Rafficer** [comment]
It is official. It just doesn't support macOS, but only Linux.

**Comment by Rafficer** [comment]
Closing as this will be implemented with 28.
