### ISSUE TITLE
[BUG] After fresh install, Command 'protonvpn' doesn't work

### ISSUE THREAD

**Issue by Paulpatou** [ProtonVPN/protonvpn-cli-ng#84]
**Describe the bug**

**To Reproduce**
1. `sudo apt install -y openvpn dialog python3-pip python3-setuptools`  Successfully
2. `sudo pip3 install protonvpn-cli `Successfully
3. `protonvpn init`
Command 'protonvpn' is available in '/usr/local/bin/protonvpn'
The command could not be located because '/usr/local/bin' is not included in the PATH environment variable.
protonvpn: command not found

With `/usr/local/bin/protonvpn` everything is good!
My /etc/environment file is correct => `PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"`

**Desktop (please complete the following information):**
 - OS: 18.04.3 LTS (LXC container on Proxmox)  
 - Python Version: Python 3.6.9
 - ProtonVPN-CLI Version: ProtonVPN-CLI v2.2.0

Thank's for help

**Comment by Rafficer** [comment]
What's the actual content of the path variable? Not what it should be.

**Comment by Paulpatou** [comment]
root@CT:~# echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin

Well, I hadn't checked and it's missing => `/usr/local/bin`
