### ISSUE TITLE
[Enhancement] docker deployment

### ISSUE THREAD

**Issue by Paulpatou** [ProtonVPN/protonvpn-cli-ng#86]
Hi

I'd like to know if there's a docker deployment planned?
I tried to make a dockerfile, the installation of protonvpn-cli-ng is good but I encounter errors in the use.
Thanks for your work.

**Comment by Rafficer** [comment]
What do you mean a docker deployment? What would be the use case for running it in docker? Do you want to use the docker container as a router?

**Comment by Paulpatou** [comment]
Yes I would like to use it as a router with a socks5 proxy, for example, danted.
I just want to automate the installation of protonvpn-cli-ng and connect it automatically to a country.

I started to make a dockerfile, everything is not perfect and for the moment not fully functional. 

```
FROM ubuntu:18.04

## Install Protonvpn-cli
RUN apt-get update && \
    apt-get -y install openvpn python dialog wget git iptables && \
    git clone "https://github.com/protonvpn/protonvpn-cli" && \
    cd protonvpn-cli && \
    ./protonvpn-cli.sh --install && \
    printf '%s\n' IDENTIFIANT_openvpn PASSWORD_openvpn 1 N Y | protonvpn-cli --init

## Protonvpn-cli-ng
#RUN apt-get install -y openvpn dialog python3-pip python3-setuptools && \
#    pip3 install protonvpn-cli

```


`docker run -it --cap-add=NET_ADMIN --device /dev/net/tun protonvpn:latest`


I tested with both versions of "protonvpn-cli" and "protonvpn-cli-ng" but I have more problems with the latest python version at the moment.

I will also try to use Alpine linux instead of ubuntu 18.04

**Comment by Rafficer** [comment]
Will OpenVPN even work out of the box in docker? If not, that's what needs to be fixed first.

To answer your question: No, I didn't plan to make it docker compatible if anything special for that is required. I don't see docker as target use case for this program.

**Comment by mxmxcz** [comment]
You might want to try to take advantage of https://github.com/haugene/docker-transmission-openvpn, which runs Transmission (irrelevant for you) in Docker and routes all traffic through openvpn (and PVPN is one of the supported providers). It should be possible to cut away the bloat around it and use just the VPN part.

**Comment by Rafficer** [comment]
As there's no reply and this is about the old CLI, I'm closing this issue.
