### ISSUE TITLE
[Enhancement] I have created a simple graphical interface (Contribution)

### ISSUE THREAD

**Issue by wuniversales** [ProtonVPN/protonvpn-cli-ng#93]
I have created a minimalistic graphic interface to eliminate the need for the use of commands.
Here I leave the project.
https://gitlab.com/universales/protonvpn-simple-gui
Please, add the unoficial Simple GUI to README.md
Regards

**Comment by kaplun** [comment]
Dear @wuniversales thanks a lot for your contribution.
At the moment, we prefer that the official CLI client of ProtonVPN does not endorse unofficial additional GUI/clients.
Feel free though to advertise your project e.g. on Reddit, so that other users can find it.
