### ISSUE TITLE
[BUG] ProtonVPN-CLI don't work

### ISSUE THREAD

**Issue by Nemial** [ProtonVPN/protonvpn-cli-ng#97]
**Describe the bug**
Any time protonvpn-clang is used, it returns the same error phrase
```
[!] There was an error connecting to the ProtonVPN API.
[!] Please make sure your connection is working properly!
```

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
[pvpn-cli.log](https://github.com/ProtonVPN/protonvpn-cli-ng/files/4140849/pvpn-cli.log)

**Desktop (please complete the following information):**
 - OS: Slackware Current
 - Python Version: 3.8.1
 - ProtonVPN-CLI Version: 2.0.0

**Comment by Rafficer** [comment]
Can you `ping api.protonmail.ch`?

Do you reside in russia at the moment, by any chance?

**Comment by Nemial** [comment]
Yes, I live in Russia. Sorry to pee, I have the latest version installed. And the site is pinged

**Comment by Rafficer** [comment]
Sadly, Russia is currently blocking all Proton Services. See more here: https://www.reddit.com/r/protonmail/comments/ewrilc/_/fg3vum8

At the moment, I don't think there's much you can do to circumvent this issue. You'd likely need to manually set up OpenVPN, if that even works.

**Comment by Nemial** [comment]
```
PING api.protonmail.ch (185.70.40.185) 56(84) bytes of data.
64 bytes from 185-70-40-185.protonmail.ch (185.70.40.185): icmp_seq=1 ttl=52 time=132 ms

--- api.protonmail.ch ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 131.599/131.599/131.599/0.000 ms
```

**Comment by Nemial** [comment]
I have OpenVPN configured. But I thought that the utility could be fixed, because a couple of days ago everything was working

**Comment by Rafficer** [comment]
Interesting. Can you open `https://api.protonmail.ch/vpn/servers` in your browser?

**Comment by Nemial** [comment]
No

**Comment by Rafficer** [comment]
That's the problem... Sadly, not much that can be done in the program.

**Comment by Rafficer** [comment]
One more question, can you open https://api.protonvpn.ch/vpn/servers in your browser?

**Comment by Rafficer** [comment]
Please update your client to v2.2.1 (just released). Changes in this release should help you.

**Comment by silasdavis** [comment]
I am trying to use the client on locked-down wifi - the operators mess with DNS and block some ports but I was hoping to tunnel out over TCP. What is the issue here are you relying on authenticated DNS here?

I currently get an HSTS error on protonvpn.com. I can ping api.protonmail.ch on 185.70.41.131 - is that address correct?

**Comment by Rafficer** [comment]
We've switched to https://api.protonvpn.ch for the time being. Both api.protonmail.ch and api.protonvpn.com work fine. There's currently no way to switch the API domain, but this will be added.

**Comment by silasdavis** [comment]
What is the API server needed for? Do you authenticate with API then pass a token? It would be nice for cases like this if you could connect directly to the VPN servers using an offline cache or their addresses. If a token is needed perhaps you could arrange to source a long lasting when you have an unblocked connection.

**Comment by Rafficer** [comment]
Used for getting a users public IP before and after a connection (to check if they changed) and getting the latest server data. It's an interesting thought to make it used cached data, though. Not sure if it's great to implement, though.

**Comment by maskari** [comment]
Hi, I have the same issue and after troubleshooting it looks like api.protonvpn.ch is blocked at my location but api.protonmail.ch is not. is there a way I can change protonvpn-cli to use protonmail.ch?
I am running ubuntu 20.04

**Comment by Rafficer** [comment]
Not right now, it's hardcoded... :confused: 

I'll see if I can add this right away, then it'll be available for the next release...

Depending on how comfortable you feel with it, you could theoretically change this yourself on the running version:

Go to the install location of the ProtonVPN-CLI (If installed via `sudo pip3 install protonvpn-cli` it should be `/usr/local/lib/python3.8/dist-packages/protonvpn_cli/`)

Edit `utils.py` in this directory

`vim utils.py`

Find the line `api_domain = "https://api.protonvpn.ch"` and change it to `api_domain = "https://api.protonmail.ch"

Save, then try again. If you break something you can just uninstall and reinstall protonvpn-cli via pip, which should restore everything :)

**Comment by maskari** [comment]
That works! Thank you very much.

**Comment by Rafficer** [comment]
@maskari This will obviously be reversed when you update the CLI next time. However, The next release should contain #173, which allows you to just specify the preferred API in the config file :)

**Comment by RiskerDegree87** [comment]
@Rafficer I Changed The Api in The Python File To api.protonmail.ch but i still get the error, i know i can ping and i can open the api.protonmail.ch in my browser, but why i've keep get this error? that was same problem for me, ubuntu 20.04 8gb ram, living in iran

**Comment by piale-chini** [comment]
Me too !

**Comment by RiskerDegree87** [comment]
so how i fix the api issue @Rafficer  ?

**Comment by saeedark** [comment]
I have same Problem.

**Comment by RiskerDegree87** [comment]
@saeedark thank you! its working fine now!

**Comment by RiskerDegree87** [comment]
@saeedark i just pressed the enter to connect to netherlands, then i got following error:
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 72, in main
    cli()
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 119, in cli
    connection.dialog()
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 123, in dialog
    openvpn_connect(server_result, protocol_result)
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 450, in openvpn_connect
    shutil.copyfile(TEMPLATE_FILE, OVPN_FILE)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/alireza/.pvpn-cli/template.ovpn'

**Comment by RiskerDegree87** [comment]
@saeedark fixed, i deleted .pvpn-cli directory in home and did "protonvpn init" again

**Comment by mohammadsalamati** [comment]
same problem in Iran:\

**Comment by ghonchesefidi** [comment]
I have the same problem in Iran. I can connect with the Andriod app and Windows version but in Linux, I have this problem.

**Comment by ghonchesefidi** [comment]
I have same Problem.
Edit: now I install 2.1.0
'''
sudo pip3 install protonvpn_cli==2.1.0
'''
it works just fine.



This worked for me 2

**Comment by ghonchesefidi** [comment]
> Not right now, it's hardcoded... 
> 
> I'll see if I can add this right away, then it'll be available for the next release...
> 
> Depending on how comfortable you feel with it, you could theoretically change this yourself on the running version:
> 
> Go to the install location of the ProtonVPN-CLI (If installed via `sudo pip3 install protonvpn-cli` it should be `/usr/local/lib/python3.8/dist-packages/protonvpn_cli/`)
> 
> Edit `utils.py` in this directory
> 
> `vim utils.py`
> 
> Find the line `api_domain = "https://api.protonvpn.ch"` and change it to `api_domain = "https://api.protonmail.ch"`
> 
> Save, then try again. If you break something you can just uninstall and reinstall protonvpn-cli via pip, which should restore everything :)

This way I got 404 error

**Comment by msalamati** [comment]
> I have same Problem.
> Edit: now I install 2.1.0
> '''
> sudo pip3 install protonvpn_cli==2.1.0
> '''
> it works just fine.
> 
> This worked for me 2

This way I got error:

Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 72, in main
    cli()
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/cli.py", line 119, in cli
    connection.dialog()
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 123, in dialog
    openvpn_connect(server_result, protocol_result)
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_cli/connection.py", line 450, in openvpn_connect
    shutil.copyfile(TEMPLATE_FILE, OVPN_FILE)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.pvpn-cli/template.ovpn'

**Comment by msalamati** [comment]
> I have same Problem.
> Edit: now I install 2.1.0
> '''
> sudo pip3 install protonvpn_cli==2.1.0
> '''
> it works just fine.
> 
> This worked for me 2

This worked for me
Thanks

**Comment by Omid-SH** [comment]
> I have same Problem.
> Edit: now I install 2.1.0
> '''
> sudo pip3 install protonvpn_cli==2.1.0
> '''
> it works just fine.
> 
> This worked for me 2

This worked in iran
Thanks a lot!!

**Comment by RiskerDegree87** [comment]
> > I have same Problem.
> > Edit: now I install 2.1.0
> > '''
> > sudo pip3 install protonvpn_cli==2.1.0
> > '''
> > it works just fine.
> > This worked for me 2
> 
> This worked in iran
> Thanks a lot!!

reply to iranians, tell them delete their comments, maybe isp,s block the secondary api if they see these comments about this error, now clean them up, do not let them know the secondary one, or they will block it and no way to use protonvpn anymore, now delete ur comment if u see this, tell others to delete the fixed problem

**Comment by RiskerDegree87** [comment]
remove iranias comments or shatel,ir irancell and others will block protonvpn secondary api

**Comment by ggrrll** [comment]
> Not right now, it's hardcoded... confused
> 
> I'll see if I can add this right away, then it'll be available for the next release...
> 
> Depending on how comfortable you feel with it, you could theoretically change this yourself on the running version:
> 
> Go to the install location of the ProtonVPN-CLI (If installed via `sudo pip3 install protonvpn-cli` it should be `/usr/local/lib/python3.8/dist-packages/protonvpn_cli/`)
> 
> Edit `utils.py` in this directory
> 
> `vim utils.py`
> 
> Find the line `api_domain = "https://api.protonvpn.ch"` and change it to `api_domain = "https://api.protonmail.ch"`
> 
> Save, then try again. If you break something you can just uninstall and reinstall protonvpn-cli via pip, which should restore everything :)

thanks @Rafficer  

just in case it might help: in my case, that line was actually 

`api_domain = get_config_value("USER", "api_domain").rstrip("/")`

which I changed as suggested (and it's working)...but I still wanted to double check (not supposed to create other issues, to the best of your knowledge @Rafficer )

**Comment by Rafficer** [comment]
This got changed, you can actually change the API domain in the config file now. So I'd advice you to undo your changes and set it in the config file. :)

**Comment by mortzi** [comment]
For the ones who stuck after downgrading from 2.2.4 to 2.1.0

I had to change the api_domain in  ~/.pvpn-cli/pvpn-cli.cfg to `api_domain = https://api.protonmail.ch` to make it work (as expected with the new change @Rafficer  mentioned)

**Comment by hamedmojiri** [comment]
i downgraded to 2.1.0 and it fixed the problem with api, so i executed the "protonvpn c" command and it responded with "Connected!" but I can't open filtered websites like youtube and facebook

> This got changed, you can actually change the API domain in the config file now. So I'd advice you to undo your changes and set it in the config file. :)

**Comment by brainode** [comment]
> i downgraded to 2.1.0 and it fixed the problem with api, so i executed the "protonvpn c" command and it responded with "Connected!" but I can't open filtered websites like youtube and facebook
> Edit : tested with 2.2.4 and changing api_domain to api.protonmail.ch, still not working
> 
> > This got changed, you can actually change the API domain in the config file now. So I'd advice you to undo your changes and set it in the config file. :)

Same thing...

**Comment by julianheres** [comment]
> Not right now, it's hardcoded... confused
> 
> I'll see if I can add this right away, then it'll be available for the next release...
> 
> Depending on how comfortable you feel with it, you could theoretically change this yourself on the running version:
> 
> Go to the install location of the ProtonVPN-CLI (If installed via `sudo pip3 install protonvpn-cli` it should be `/usr/local/lib/python3.8/dist-packages/protonvpn_cli/`)
> 
> Edit `utils.py` in this directory
> 
> `vim utils.py`
> 
> Find the line `api_domain = "https://api.protonvpn.ch"` and change it to `api_domain = "https://api.protonmail.ch"`
> 
> Save, then try again. If you break something you can just uninstall and reinstall protonvpn-cli via pip, which should restore everything :)

Additionally to this I also changed _cli.py_ which also keeps a reference to protonvpn domain, in my case blocked by Fortinet at a Starbucks location. 
Had to do it because on running the _init_ task it grabs the domain from the local variable defined at method _init_cli_
So I gather both places need to be changed, both for bootstrapping and also for regular connection.
The overriding of the variable at _.pvpn-cli/pvpn-cli.cfg_ didn't work for me.

**Comment by mmdmine** [comment]
I'm getting same error, because ProtonVPN APIs are blocked in my region. I can connect on Windows and Android but protonvpn-cli client is not working.

**Comment by mortzi** [comment]
@mmdmine Living in the same region, I can connect. Make sure you have this `api_domain = https://api.protonmail.ch`

**Comment by mmdmine** [comment]
> @mmdmine Living in the same region, I can connect. Make sure you have this `api_domain = https://api.protonmail.ch`

It was using `api.protonvpn.ch`, I changed it to what you said, and now it got fixed. Thank you!

**Comment by azimmsd** [comment]
Thank you guys @mortzi @julianheres @Rafficer ! I was just going crazy.

**Comment by sanjrani** [comment]
I was facing the same problem same connection problem and i was using protonvpn-cli 2.2.4 version so removed 2.2.4 and installed 2.1.0 now it is working fine.
Thank you to everyone @Rafficer

**Comment by saeedahm** [comment]
hi i can install protonvpn in windows and i can work with it but i cant connect protonvpn in linux

i get this error
[!] There was an error connecting to the ProtonVPN API.
[!] Please make sure your connection is working properly!
 what should i do?

**Comment by mehdigrant** [comment]
> @mmdmine Living in the same region, I can connect. Make sure you have this `api_domain = https://api.protonmail.ch`

I didn't find api_domain anywhere !!
How should i do it ?

**Comment by ehsanshekari** [comment]
> Not right now, it's hardcoded... 
> 
> I'll see if I can add this right away, then it'll be available for the next release...
> 
> Depending on how comfortable you feel with it, you could theoretically change this yourself on the running version:
> 
> Go to the install location of the ProtonVPN-CLI (If installed via `sudo pip3 install protonvpn-cli` it should be `/usr/local/lib/python3.8/dist-packages/protonvpn_cli/`)
> 
> Edit `utils.py` in this directory
> 
> `vim utils.py`
> 
> Find the line `api_domain = "https://api.protonvpn.ch"` and change it to `api_domain = "https://api.protonmail.ch"`
> 
> Save, then try again. If you break something you can just uninstall and reinstall protonvpn-cli via pip, which should restore everything :)

I also changed the api_domain to https://api.protonmail.ch in cli.py then it starts working
